### PR TITLE
Added Python 2.7+ support including unittest and Travis CI support.

### PR DESCRIPTION
**Pull request by arcturusannamalai**
Updated with tests and minor code changes. Code porting to Python shown to successful tests in various versions also.
https://travis-ci.org/Ezhil-Language-Foundation/tamil-sandhi-checker/builds/343613252

### CODE REVIEW

**Comment by arcturusannamalai** [comment]
Closing due to too many merge conflicts.

**Comment by nithyadurai87** [comment]
I am yet to learn merging and resolving conflicts.

Thanks for the pull request.

Will explore them and add them in existing code manually.

**Comment by arcturusannamalai** [comment]
Thanks. I will plan to merge with your changes and issue new PR.
Best Regards.

**Comment by nithyadurai87** [comment]
Thanks.

I am done with my changes.

Now you can do your changes and give a pull request.

2018-03-11 20:31 GMT+05:30 Muthiah Annamalai <notifications@github.com>:

**Comment by arcturusannamalai** [comment]
OK

**Comment by nithyadurai87** [comment]
Merged the pull request.

Thanks a lot.

**Pull request closed without merging**
